config/default.config.yaml
src/config.js
src/index.js

These changes will allow us to specify the host to listen on - so we don't bind to public IPs without explicit configuration to do so.
I couldn't see a "IP" in the Joi documentation, so going with string (and assuming there'll be a failure if we cannot bind to it).
Tested in a vagrant container and verified by netstat:
```
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      -
```
New log line looks like so:
```
Jun 06 09:41:36 jessie npm[5734]: Listening on 127.0.0.1:9000
```

Update config to allow binding to a host

---

src/handlers.js

otherwise we send an empty Content-Disposition, causing some browsers
to download instead of view images.

Only proxy Content-X headers if truthy

---

src/handlers.js

Instead of writing downloaded files to /tmp (or configured dir) itself.

Fix to ensure writing to /tmp/av-XXXXX when downloading

---

config/default.config.yaml
src/config.js
src/handlers.js
src/reporting.js

This option effectively sets the `baseUrl` for a given request for media
with the domain replaced with the media's domain. This forces a direct
download from the media's content repo.
`baseUrl` is effectively unused with this option enabled, but this is
probably better than enabling `directDownload` when `baseUrl` is not
specified. The option should only be used in the minority of cases
where the content scanner has restricted access to a set of trusted
content repositories so as to prevent downloading and scanning of
content from *any* domain.

Implement `directDownload` config option for downloading from media domain 

---

config/default.config.yaml
src/config.js
src/handlers.js
src/with-temp-dir.js

When temporary files are unlinked from the filesystem, execute
`altRemovalCmd` with the file as the first argument instead of using
node's unlink function.

Implement config option to replace node's unlink function

---

src/handlers.js
test/handlers-test.js

If merged, my `npm test` fails with a timeout.

Bugfix for hanging scan when using altRemovalCmd

---

README.md
src/app.js
src/client-error.js
src/decrypt-body.js
src/handlers.js
src/joi-error.js
src/middlewares.js
src/reporting.js
test/middlewares-test.js

For example, clients can now distinguish between `MCS_BAD_DECRYPTION` and `MCS_MEDIA_NOT_CLEAN` (which are both error code 403).

Add reasons to client errors for disambiguation

---

README.md

Fix git web url for olm

---

src/reporting.js

If decryption is not required, copy the file anyway so the logic
around removing the "decrypted" version as soon as possible will still function.
This allows us to serve the file we recieved from the media_repo back to the client, even if
that file was originally undecrypted.
Taking this approach means we do not need an if block to handle the two cases of decrypted and encrypted source files, which makes this easier to reason about.
I believe this fixes #30

Make a copy of unencrypted files before scanning

---

src/reporting.js

If the acceptedMimeType option is not present on the configuration file, the MCS will not copy the file in the tmp directory for the analyse.
This commit will correct this.
Signed-off-by: Léo Mora [l.mora@outlook.fr](l.mora@outlook.fr)

Fixing a bug where the file is not copied for analyse if the acceptedMimeType option is not present

---

test/handlers-test.js
test/reporting-test.js

The CI was failing when the script is 'exit X' because the content scanner tries to invoke it with the file to scan as its last parameter.
This fixes it by adding the character '#' to the script passed through the config in these cases, so that any further parameter is considered a comment and isn't interpreted by bash.

Fix unit tests

---

src/decrypt.js

Fix #37 by implementing https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/#variant-1

Fix compatibility issues with Buffer

---

.gitignore
Dockerfile

Drops the image size from 1GB to 129MB. Does not include vim or secure-delete - are these actually needed in a production deployment?
Test pass on Node 14 which is the current LTS.

Multi-stage Dockerfile for a smaller build & update to Node 14

---

README.md
package.json
src/app.js
src/decrypt-body.js
test/decrypt-body-test.js
test/handlers-test.js
test/middlewares-test.js

We were using Olm v2 still. This PR updates the dependency of Olm to the latest version (v3.2.3).
As this is bumping a major version of Olm, there was a breaking change. Namely that the [olm library must now be initialised](https://gitlab.matrix.org/matrix-org/olm/-/blob/master/CHANGELOG.rst). I opted to do so in `createApp`, and assigned the initialised `Olm` object to NodeJS's `global` object, which is accessible across the current process.
The tests were a bit messier. I couldn't easily figure out a nice place to initialise Olm once for all tests. So instead, we initialise in each test file where necessary.

Update olm to v3.x

---

Dockerfile
config/docker.config.yaml

The switch to Alpine in #40 proved problematic in some custom stuff that we needed in EMS land. The Debian base is more versatile to build on.
This also allows using `secure-delete` to remove temporary files which was also difficult to pull into Alpine.

Switch back to Debian based docker image

---

src/reporting.js

*  Fix decrypted file mimetype checks
The decrypted path only fails the file on unknown mimetype if we're actually configured with a list of mimetypes. Add the missing `if` to look at that config.
Also add a bit of logging when files are skipped due to mimetype and make some let's const, since we don't redeclare them.
* Fix checking of mimetype for decrypted files
The "includes" check was being made against `mimetype` which is an object, when it should be made against `mimetype.mime`.

Fixes for decrypted file mimetype checks

---

src/reporting.js

Fixes https://github.com/matrix-org/matrix-content-scanner/issues/50.
This field is not actually specced. The specced field is at content.info.mimetype, which [isn't currently sent to the content scanner](https://github.com/matrix-org/matrix-content-scanner#post-download_encrypted).
We check the mimetype of the file by scanning the file itself. As issue #49 mentions, this check is not infallible, but that should be fixed separately.

Don't check the mimetype via content.file.mimetype

---

config/default.config.yaml
config/docker.config.yaml
src/config.js
src/reporting.js
test/reporting-test.js

This is to avoid caching an accidental failure due to the AV being down (e.g. restarting etc).
Will require https://github.com/matrix-org/matrix-dinsic/pull/829 to be merged and deployed before being usable on DINUM's infra.
Fixes #56

Allow defining error codes ignored by the cache

---

src/reporting.js

Fixes https://github.com/matrix-org/matrix-content-scanner/issues/55
It looks like the code assumes `reject` returns after handling an error, which doesn't seem to be the case in javascript.
Also improve the error handling a bit so the client doesn't get `Unhandled server error`.
Introduced in https://github.com/matrix-org/matrix-content-scanner/pull/47

Return after handling an error when getting a file

---

package.json
src/reporting.js
test/handlers-test.js

Fixes #49.
Testing locally, it reports JSON, JS and YAML files as `text/plain` — which surprised me somewhat because `file` appears to be able to do more and uses the same library.
Still investigating — wonder if it needs to be told to use the system's magic file...

Use mmmagic for MIME type sniffing

---

config/default.config.yaml

Thought it was worth explicitly pointing this out. The content scanner doesn't make any effort to scrub the files or anything (this might be doable as an external script but it's not built in and you ought not to rely on it too much!)

Add warning about MIME type sniffing and security
